### ISSUE TITLE
docker-compose: The server does not support SSL connections

### ISSUE THREAD

**Issue by bbigras** [gorules/zen#106]
with
```yaml
version: '3.8'

services:
  admin:
    image: 'gorules/brms'
    ports:
      - '9080:80'
    depends_on:
      - pg-database
    environment:
      DB_HOST: pg-database
      DB_PORT: 5432
      DB_USER: my-user
      DB_PASSWORD: my-password
      DB_NAME: test-db
      LICENSE_KEY: 'my-license-key' # Obtain it from https://portal.gorules.io

  pg-database:
    image: 'postgres'
    environment:
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: test-db
    ports:
      - '5432:5432'
```

```
❯ docker compose logs admin
test-gorules-admin-1  | {"level":50,"time":1701542183664,"pid":1,"hostname":"dd89ea76ebce","name":"system","err":{"type":"Error","message":"connect ECONNREFUSED 172.19.0.2:5432","stack":"Error: connect ECONNREFUSED 172.19.0.2:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)","errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"172.19.0.2","port":5432},"msg":"application startup error"}
test-gorules-admin-1  | {"level":50,"time":1701542237643,"pid":1,"hostname":"dd89ea76ebce","name":"system","err":{"type":"Error","message":"The server does not support SSL connections","stack":"Error: The server does not support SSL connections\n    at Socket.<anonymous> (/app/node_modules/.pnpm/pg@8.11.2/node_modules/pg/lib/connection.js:77:37)\n    at Object.onceWrapper (node:events:632:26)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:335:12)\n    at readableAddChunk (node:internal/streams/readable:308:9)\n    at Readable.push (node:internal/streams/readable:245:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"},"msg":"application startup error"}
test-gorules-admin-1  | {"level":50,"time":1701542311228,"pid":1,"hostname":"dd89ea76ebce","name":"system","err":{"type":"Error","message":"The server does not support SSL connections","stack":"Error: The server does not support SSL connections\n    at Socket.<anonymous> (/app/node_modules/.pnpm/pg@8.11.2/node_modules/pg/lib/connection.js:77:37)\n    at Object.onceWrapper (node:events:632:26)\n    at Socket.emit (node:events:517:28)\n    at addChunk (node:internal/streams/readable:335:12)\n    at readableAddChunk (node:internal/streams/readable:308:9)\n    at Readable.push (node:internal/streams/readable:245:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"},"msg":"application startup error"}
```
