### ISSUE TITLE
invalid license

### ISSUE THREAD

**Issue by sk92129** [gorules/zen#347]
I created an online account at portal.gorules.io and generated a license.

I used that license to run gorules zen locally via docker.

Here is my script:

```
version: '3.8'

services:
  admin:
    image: 'gorules/brms'
    ports:
      - '9080:80'
    depends_on:
      - pg-database
    environment:
      DB_HOST: pg-database
      DB_PORT: 5432
      DB_USER: my-user
      DB_PASSWORD: my-password
      DB_NAME: test-db
      DB_SSL_DISABLED: true
      LICENSE_KEY: '<replace with my license>' # Obtain it from https://portal.gorules.io
      

  pg-database:
    image: 'postgres'
    environment:
      POSTGRES_USER: my-user
      POSTGRES_PASSWORD: my-password
      POSTGRES_DB: test-db
    ports:
      - '5432:5432'
```

It ran fine the first time.  Then I tried to add this:

```
    environment:
      LOG_LEVEL: debug              <===
```

Then with or without this LOG_LEVEL, gorules zen spits out this error message:

```
admin-1        | {"level":30,"time":1746737453722,"pid":1,"hostname":"a11836acab11","name":"system","msg":"application starting"}
admin-1        | (node:1) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
admin-1        | (Use `node --trace-deprecation ...` to show where the warning was created)
admin-1        | {"level":30,"time":1746737453803,"pid":1,"hostname":"a11836acab11","name":"system","msg":"connecting to database on pg-database:5432"}
admin-1        | {"level":30,"time":1746737454047,"pid":1,"hostname":"a11836acab11","name":"system","msg":"database connected on pg-database:5432"}
admin-1        | {"level":30,"time":1746737454048,"pid":1,"hostname":"a11836acab11","name":"system","msg":"checking license"}
admin-1        | {"level":30,"time":1746737454075,"pid":1,"hostname":"a11836acab11","name":"system","msg":"initial organisation created"}
admin-1        | {"level":50,"time":1746737454773,"pid":1,"hostname":"a11836acab11","name":"system","error":"Bad Request","statusCode":400,"message":"environment_credentials_mismatch","details":{"disconnectLicense":true},"msg":"failed to fetch license"}
admin-1        | {"level":50,"time":1746737454778,"pid":1,"hostname":"a11836acab11","name":"system","err":{"type":"Error","message":"incorrect license, failed to start the service","stack":"Error: incorrect license, failed to start the service\n    at /app/3.js:1831:35603\n    at step (/app/3.js:1831:33829)\n    at Object.next (/app/3.js:1831:33131)\n    at database_asyncGeneratorStep (/app/3.js:1831:32237)\n    at _next (/app/3.js:1831:32464)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)"},"msg":"application startup error"}
```

What is going wrong?  

I checked the value of the license when I go back to portal.gorules.io ---- and the value is the same.

Any ideas?
